global using NUnit.Framework;

namespace WhileStatements.Tests
{
    [TestFixture]
    public class ArithmeticSequencesTests
    {
        [TestCase(0, 0, ExpectedResult = 0)]
        [TestCase(1, 0, ExpectedResult = 0)]
        [TestCase(1, 1, ExpectedResult = 1)]
        [TestCase(1, 2, ExpectedResult = 3)]
        [TestCase(1, 3, ExpectedResult = 6)]
        [TestCase(1, 4, ExpectedResult = 10)]
        [TestCase(1, 5, ExpectedResult = 15)]
        [TestCase(2, 0, ExpectedResult = 0)]
        [TestCase(2, 1, ExpectedResult = 2)]
        [TestCase(2, 2, ExpectedResult = 5)]
        [TestCase(2, 3, ExpectedResult = 9)]
        [TestCase(2, 4, ExpectedResult = 14)]
        [TestCase(2, 5, ExpectedResult = 20)]
        [TestCase(3, 0, ExpectedResult = 0)]
        [TestCase(3, 1, ExpectedResult = 3)]
        [TestCase(3, 2, ExpectedResult = 7)]
        [TestCase(3, 3, ExpectedResult = 12)]
        [TestCase(3, 4, ExpectedResult = 18)]
        [TestCase(3, 5, ExpectedResult = 25)]
        [TestCase(4, 0, ExpectedResult = 0)]
        [TestCase(4, 1, ExpectedResult = 4)]
        [TestCase(4, 2, ExpectedResult = 9)]
        [TestCase(4, 3, ExpectedResult = 15)]
        [TestCase(4, 4, ExpectedResult = 22)]
        [TestCase(4, 5, ExpectedResult = 30)]
        [TestCase(5, 0, ExpectedResult = 0)]
        [TestCase(5, 1, ExpectedResult = 5)]
        [TestCase(5, 2, ExpectedResult = 11)]
        [TestCase(5, 3, ExpectedResult = 18)]
        [TestCase(5, 4, ExpectedResult = 26)]
        [TestCase(5, 5, ExpectedResult = 35)]
        public int SumArithmeticSequenceTerms1_ReturnsSum(int a, int n)
        {
            return ArithmeticSequences.SumArithmeticSequenceTerms1(a, n);
        }

        [TestCase(0, ExpectedResult = 0)]
        [TestCase(1, ExpectedResult = 17)]
        [TestCase(2, ExpectedResult = 67)]
        [TestCase(3, ExpectedResult = 150)]
        [TestCase(4, ExpectedResult = 266)]
        [TestCase(5, ExpectedResult = 415)]
        [TestCase(6, ExpectedResult = 597)]
        [TestCase(7, ExpectedResult = 812)]
        [TestCase(8, ExpectedResult = 1060)]
        [TestCase(9, ExpectedResult = 1341)]
        [TestCase(10, ExpectedResult = 1655)]
        public int SumArithmeticSequenceTerms2_ReturnsSum(int n)
        {
            return ArithmeticSequences.SumArithmeticSequenceTerms2(n);
        }

        [TestCase(0, 0, ExpectedResult = 0)]
        [TestCase(1, 0, ExpectedResult = 0)]
        [TestCase(1, 1, ExpectedResult = 1)]
        [TestCase(1, 2, ExpectedResult = 5)]
        [TestCase(1, 3, ExpectedResult = 12)]
        [TestCase(1, 4, ExpectedResult = 22)]
        [TestCase(1, 5, ExpectedResult = 35)]
        [TestCase(2, 0, ExpectedResult = 0)]
        [TestCase(2, 1, ExpectedResult = 2)]
        [TestCase(2, 2, ExpectedResult = 7)]
        [TestCase(2, 3, ExpectedResult = 15)]
        [TestCase(2, 4, ExpectedResult = 26)]
        [TestCase(2, 5, ExpectedResult = 40)]
        [TestCase(3, 0, ExpectedResult = 0)]
        [TestCase(3, 1, ExpectedResult = 3)]
        [TestCase(3, 2, ExpectedResult = 9)]
        [TestCase(3, 3, ExpectedResult = 18)]
        [TestCase(3, 4, ExpectedResult = 30)]
        [TestCase(3, 5, ExpectedResult = 45)]
        [TestCase(4, 0, ExpectedResult = 0)]
        [TestCase(4, 1, ExpectedResult = 4)]
        [TestCase(4, 2, ExpectedResult = 11)]
        [TestCase(4, 3, ExpectedResult = 21)]
        [TestCase(4, 4, ExpectedResult = 34)]
        [TestCase(4, 5, ExpectedResult = 50)]
        [TestCase(5, 0, ExpectedResult = 0)]
        [TestCase(5, 1, ExpectedResult = 5)]
        [TestCase(5, 2, ExpectedResult = 13)]
        [TestCase(5, 3, ExpectedResult = 24)]
        [TestCase(5, 4, ExpectedResult = 38)]
        [TestCase(5, 5, ExpectedResult = 55)]
        public int SumArithmeticSequenceTerms3_ReturnsSum(int a, int n)
        {
            return ArithmeticSequences.SumArithmeticSequenceTerms3(a, n);
        }

        [TestCase(0, 0, 0, ExpectedResult = 0)]
        [TestCase(1, 0, 0, ExpectedResult = 0)]
        [TestCase(1, 0, 1, ExpectedResult = 1)]
        [TestCase(1, 0, 2, ExpectedResult = 2)]
        [TestCase(1, 0, 3, ExpectedResult = 3)]
        [TestCase(1, 0, 4, ExpectedResult = 4)]
        [TestCase(1, 0, 5, ExpectedResult = 5)]
        [TestCase(1, 1, 0, ExpectedResult = 0)]
        [TestCase(1, 1, 1, ExpectedResult = 1)]
        [TestCase(1, 1, 2, ExpectedResult = 3)]
        [TestCase(1, 1, 3, ExpectedResult = 6)]
        [TestCase(1, 1, 4, ExpectedResult = 10)]
        [TestCase(1, 1, 5, ExpectedResult = 15)]
        [TestCase(1, 2, 0, ExpectedResult = 0)]
        [TestCase(1, 2, 1, ExpectedResult = 1)]
        [TestCase(1, 2, 2, ExpectedResult = 4)]
        [TestCase(1, 2, 3, ExpectedResult = 9)]
        [TestCase(1, 2, 4, ExpectedResult = 16)]
        [TestCase(1, 2, 5, ExpectedResult = 25)]
        [TestCase(1, 3, 0, ExpectedResult = 0)]
        [TestCase(1, 3, 1, ExpectedResult = 1)]
        [TestCase(1, 3, 2, ExpectedResult = 5)]
        [TestCase(1, 3, 3, ExpectedResult = 12)]
        [TestCase(1, 3, 4, ExpectedResult = 22)]
        [TestCase(1, 3, 5, ExpectedResult = 35)]
        [TestCase(1, 4, 0, ExpectedResult = 0)]
        [TestCase(1, 4, 1, ExpectedResult = 1)]
        [TestCase(1, 4, 2, ExpectedResult = 6)]
        [TestCase(1, 4, 3, ExpectedResult = 15)]
        [TestCase(1, 4, 4, ExpectedResult = 28)]
        [TestCase(1, 4, 5, ExpectedResult = 45)]
        [TestCase(1, 5, 0, ExpectedResult = 0)]
        [TestCase(1, 5, 1, ExpectedResult = 1)]
        [TestCase(1, 5, 2, ExpectedResult = 7)]
        [TestCase(1, 5, 3, ExpectedResult = 18)]
        [TestCase(1, 5, 4, ExpectedResult = 34)]
        [TestCase(1, 5, 5, ExpectedResult = 55)]
        [TestCase(5, 1, 0, ExpectedResult = 0)]
        [TestCase(5, 1, 1, ExpectedResult = 5)]
        [TestCase(5, 1, 2, ExpectedResult = 11)]
        [TestCase(5, 1, 3, ExpectedResult = 18)]
        [TestCase(5, 1, 4, ExpectedResult = 26)]
        [TestCase(5, 1, 5, ExpectedResult = 35)]
        [TestCase(5, 5, 0, ExpectedResult = 0)]
        [TestCase(5, 5, 1, ExpectedResult = 5)]
        [TestCase(5, 5, 2, ExpectedResult = 15)]
        [TestCase(5, 5, 3, ExpectedResult = 30)]
        [TestCase(5, 5, 4, ExpectedResult = 50)]
        [TestCase(5, 5, 5, ExpectedResult = 75)]
        public int SumArithmeticSequenceTerms4_ReturnsSum(int a, int d, int n)
        {
            return ArithmeticSequences.SumArithmeticSequenceTerms4(a, d, n);
        }
    }
}
